name: Build & Release Resource Pack

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    concurrency:
      group: resource-pack-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare Metadata
        id: meta
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          TAG="aragokt-$(date -u +%Y%m%d-%H%M)-$SHORT_SHA"
          ZIP="aragokt-${SHORT_SHA}.zip"
          REPO="${GITHUB_REPOSITORY}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "zip=$ZIP" >> "$GITHUB_OUTPUT"
          echo "repo=$REPO" >> "$GITHUB_OUTPUT"

      - name: Create ZIP
        run: |
          set -euo pipefail
          test -f pack.mcmeta || { echo "pack.mcmeta not found at repo root"; exit 1; }
          zip -r "${{ steps.meta.outputs.zip }}" . \
            -x ".git/*" \
               ".github/*" \
               "sources/*" \
               "*.md" \
               "LICENSE" \
               "LICENSE.*" \
               "README*" \
               "*.psd" "*.xcf" \
               ".DS_Store"

      - name: Compute SHA-1
        id: hash
        run: |
          set -euo pipefail
          SHA1="$(sha1sum "${{ steps.meta.outputs.zip }}" | awk '{print $1}')"
          echo "sha1=$SHA1" >> "$GITHUB_OUTPUT"
          echo "$SHA1" > "${{ steps.meta.outputs.zip }}.sha1"
          echo "$SHA1  ${{ steps.meta.outputs.zip }}" > "${{ steps.meta.outputs.zip }}.sha1sum"
          echo "resource-pack-sha1=$SHA1" > resource-pack-server.properties.snippet

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            **Minecraft Resource Pack Release**

            **Direct Download URL:**
            ```
            https://github.com/${{ steps.meta.outputs.repo }}/releases/download/${{ steps.meta.outputs.tag }}/${{ steps.meta.outputs.zip }}
            ```

            **SHA-1:**
            ```
            ${{ steps.hash.outputs.sha1 }}
            ```

            **server.properties:**
            ```
            resource-pack=https://github.com/${{ steps.meta.outputs.repo }}/releases/download/${{ steps.meta.outputs.tag }}/${{ steps.meta.outputs.zip }}
            resource-pack-sha1=${{ steps.hash.outputs.sha1 }}
            ```
          files: |
            ${{ steps.meta.outputs.zip }}
            ${{ steps.meta.outputs.zip }}.sha1
            ${{ steps.meta.outputs.zip }}.sha1sum
            resource-pack-server.properties.snippet
