name: Build & Release Resource Pack

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    concurrency:
      group: resource-pack-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Bump Tag
        id: bump
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch

      - name: Prepare Metadata
        id: meta
        run: |
          ZIP="aragok-resource-pack-${{ steps.bump.outputs.new_tag }}.zip"
          REPO="${GITHUB_REPOSITORY}"
          echo "zip=$ZIP" >> "$GITHUB_OUTPUT"
          echo "repo=$REPO" >> "$GITHUB_OUTPUT"

      - name: Create ZIP
        run: |
          set -euo pipefail
          test -f pack.mcmeta || { echo "pack.mcmeta not found at repo root"; exit 1; }
          zip -r "${{ steps.meta.outputs.zip }}" . \
            -x ".git/*" \
               ".github/*" \
               "sources/*" \
               "*.md" \
               "LICENSE" \
               "LICENSE.*" \
               "README*" \
               "*.psd" "*.xcf" \
               ".DS_Store"

      - name: Compute SHA-1
        id: hash
        run: |
          set -euo pipefail
          SHA1="$(sha1sum "${{ steps.meta.outputs.zip }}" | awk '{print $1}')"
          echo "sha1=$SHA1" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          generate_release_notes: true
          append_body: true
          body: |
            **aragok Resource Pack Release**

            **Direct Download URL:**
            ```
            https://github.com/${{ steps.meta.outputs.repo }}/releases/download/${{ steps.bump.outputs.new_tag }}/${{ steps.meta.outputs.zip }}
            ```

            **server.properties:**
            ```
            resource-pack=https://github.com/${{ steps.meta.outputs.repo }}/releases/download/${{ steps.bump.outputs.new_tag }}/${{ steps.meta.outputs.zip }}
            resource-pack-sha1=${{ steps.hash.outputs.sha1 }}
            ```
          files: |
            ${{ steps.meta.outputs.zip }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
